When trying to deploy a ROR application to a running V3 instance, was getting  java.lang.NoClassDefFoundError: com/sun/logging/LogDomains from com.sun.enterprise.rails.RailsContainer.<init>(RailsContainer.java:49) Hence added a dependency in the pom.xml to pick up the common-util module to get a hold of the LogDomains class.
svn path=/trunk/; revision=18790