writeReport was throwing away the cause (Throwable) for failed commands. Now it sends back Throwable.toString as an attribute nam,ed "cause"
CLI Output:

----------------- BEFORE --------------------
FAILURE : GlassFish 10.0-SNAPSHOT (build b001)
---------------------------------------------

----------------- AFTER --------------------
FAILURE : GlassFish 10.0-SNAPSHOT (build b001)
java.lang.RuntimeException: test error here!!!
---------------------------------------------



svn path=/trunk/; revision=19484