Addressing class loading issues on IBM JDK. ServiceLoader on IBM JDK is throwing NoClassdefFoundError instead of ServiceConfigurationError
svn path=/trunk/; revision=47548


Former-commit-id: 4d74f3cae5aaef3b5755983d0de99a9af15bdb02