Fixed test, whose web.xml was declaring     <listener>         <listener-class>test.ServletTest</listener-class>     </listener> even though the specified listener-class did not implement any of the required listener interfaces. This kind of error used to get swallowed, but is now being reported as a side-effect of the new ServletContext#createListener:
java.lang.ClassCastException: test.ServletTest cannot be cast to java.util.EventListener
        at org.apache.catalina.core.StandardContext.createListener(StandardContext.java:2733)
        at org.apache.catalina.core.StandardContext.loadListener(StandardContext.java:4659)
        at com.sun.enterprise.web.WebModule.loadListener(WebModule.java:1609)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4569)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5316)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:509)


svn path=/trunk/; revision=29298


Former-commit-id: fb3ef59fcf2e8fe06cd9592c57b5b30b603a1c43