- resurrected the transitive dependency support, as this is way too much pain for people.   their code compiles just fine, yet they fail at the runtime with NoClassDefFoundError.   The worst part is that you won't see this problem until you exercise the very line that uses the class.
- removed synchronization on ClassLoaderProxy in favor of CopyOnWriteArrayList. This is a
  reasonable choice, as these values are read far more often than updated.

- Fixed a bug where the repository was doubly initialized. I honestly don't understand how this was working.
  I saw that this effectively puts every service twice into the habitat.

- The asadmin-cli module is packaged as an hk2-jar, yet it includes several other modules in Class-Path.
  This appears to be a concious choice, so that when this jar runs as "java -jar admin-cli.jar" we can
  find all the necessary classes. Unfortunately, this also causes the service double-instantiation problem,
  so I changed HK2 not to look at metadata from Class-Path if the referenced module is another HK2.