Issue 11589. More lenient with NoClassDefFoundError during annotation processing, log a warning and continue instead of aborting the processing. Ran QL, deployment dev tests.
svn path=/trunk/; revision=35714


Former-commit-id: 23dddaffe6e2871e218e28a22ea42569d602d1c3