Addressing class loading issues on IBM JDK. ServiceLoader on IBM JDK is throwing NoClassdefFoundError instead of ServiceConfigurationError
svn path=/branches/3.1.1/; revision=47547


Former-commit-id: 1eb82bb952c830f93ffde67d395c26e78d8237cc