Removing dependency on gmbal-api.  This an old API and should not be used.  We should use the exising gmbal.  Otherwise, gmbal-api.jar will conflict with the existing gmbal.jar, and will see a NoSuchMethodError.  This is breaking the monitoring mbeans.
svn path=/trunk/; revision=29155


Former-commit-id: 883bea87902fb3d36638f343e953a637ada2ace0