Try adding a pom type project as a direct dependency in a hk2 module and hk2-maven-plugin would crash with following exception:
[INFO] [hk2:package]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error assembling JAR

Embedded error: Failed to open /.m2/repository/org/glassfish/persistence/eclipselink-wrapper/3.0-SNAPSHOT/eclipselink-wrapper-3.0-SNAPSHOT.pom
error in opening zip file
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error assembling JAR
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
   at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
   at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
   at java.lang.reflect.Method.invoke(Method.java:597)
   at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
   at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
   at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
   at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error assembling JAR
   at com.sun.enterprise.module.maven.PackageMojo.createArchive(PackageMojo.java:208)
   at com.sun.enterprise.module.maven.PackageMojo.execute(PackageMojo.java:218)
   at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
   at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
   ... 16 more
Caused by: java.io.IOException: Failed to open /.m2/repository/org/glassfish/persistence/eclipselink-wrapper/3.0-SNAPSHOT/eclipselink-wrapper-3.0-SNAPSHOT.pom
   at com.sun.enterprise.module.common_impl.Jar$Archive.<init>(Jar.java:164)
   at com.sun.enterprise.module.common_impl.Jar.create(Jar.java:83)
   at com.sun.enterprise.module.maven.Packager.configureManifest(Packager.java:126)
   at com.sun.enterprise.module.maven.PackageMojo.createArchive(PackageMojo.java:187)
   ... 19 more
Caused by: java.util.zip.ZipException: error in opening zip file
   at java.util.zip.ZipFile.open(Native Method)
   at java.util.zip.ZipFile.<init>(ZipFile.java:114)
   at java.util.jar.JarFile.<init>(JarFile.java:133)
   at java.util.jar.JarFile.<init>(JarFile.java:97)
   at com.sun.enterprise.module.common_impl.Jar$Archive.<init>(Jar.java:160)
   ... 22 more 


It happens, because it tries to read a .pom file as a .jar file. The fix is to ignore such errors.