Fixed the broken admin app to use the "Application-Ref" now.
Can't test it end-to-end yet, because application does not load owing to:
i
SEVERE: Cannot start container  web
java.util.MissingResourceException: Can't find bundle for base name org.apache.coyote.tomcat5.LocalStrings, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:836)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:805)


Hope that gets fixed soon.

The QL is not impacted by this change as the changes come into effect
only after you access the admin app url.

Approver: Jerome.


svn path=/trunk/; revision=19571