As it turns out @Param can't handle string-int conversion automatically.  I made the option a String and then the execute() method converts it to int.
c:\glassfishv3\glassfish>asadmin list-instances
org.glassfish.api.admin.CommandException: remote failure: Can not set int field com.sun.enterprise.v3.admin.cluster.ListInstancesCommand.tim
eoutInMsec to java.lang.String

svn path=/trunk/; revision=37064


Former-commit-id: d1b55114b6b16087e378818ab43fe9ca3d253816